name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: sudo apt install libglfw3 libglfw3-dev
    - run: ./configure
    - run: make
    - run: mv calculator.exe calc_linux.exe
    - uses: actions/upload-artifact@v3
      with:
        name: linux_binary
        path: calc_linux.exe
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: brew install glfw
    - run: ./configure
    - run: make
    - run: mkdir dmg
    - run: mv calculator.exe dmg
    - run: hdiutil create -volname exec -srcfolder dmg -ov -format UDZO calculator.dmg
    - uses: actions/upload-artifact@v3
      with:
        name: macos_binary
        path: calculator.dmg
  publish:
    needs: [build_macos, build_linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: linux_binary
    - uses: actions/download-artifact@v3
      with:
        name: macos_binary
    - uses: ncipollo/release-action@v1
      with:
        name: ${{ github.event.head_commit.message }}
        tag: ${{ github.run_number }}
        commit: "master"
        artifacts: "calc_linux.exe, calculator.dmg"