name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pull repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install glfw3
      run: sudo apt install libglfw3 libglfw3-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: hub release create -m "${{ github.event.head_commit.message }}" "$(date +%Y%m%d%H%M%S)"