name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pull repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install glfw3
      run: sudo apt install libglfw3 libglfw3-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: publish
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: ${{ github.event.head_commit.message }}