name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: pull repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install glfw3
      run: sudo apt install libglfw3 libglfw3-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: publish
      uses: ncipollo/release-action@v1
      with:
        name: ${{ github.event.head_commit.message }}
        tag: ${{ github.run_number }}
        commit: "master"
        artifacts: "calculator.exe"